/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Stm32L053xx.h>
#include <stm32L053xx_drivers.h>
#include <stdlib.h>

void delay(){
	for(uint32_t i = 0 ; i<500000 ; i++);
}

int main(void)
{
	GPIO_Handle_t *GPIO_Handle_A = malloc(sizeof(*GPIO_Handle_A));
	GPIO_Handle_A->pGPIO = GPIOA; // Pin num = 5 , Pin mode out , pin speed high , pu ,
	GPIO_Handle_A->GPIO_PinConfig.GPIO_pinNumber = GPIO_PIN_NO_5;
	GPIO_Handle_A->GPIO_PinConfig.GPIO_pinMode = GPIO_MODE_OUT;
	GPIO_Handle_A->GPIO_PinConfig.GPIO_pin_speed = GPIO_SPEED_FAST;
	GPIO_Handle_A->GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_Handle_A->GPIO_PinConfig.PinPupdControl = GPIO_PU;

	GPIO_PeriClockControl(GPIO_Handle_A->pGPIO,1);
	GPIO_Init(GPIO_Handle_A);

	GPIO_Handle_t *GPIO_Handle_C_Btn = malloc(sizeof(*GPIO_Handle_C_Btn));
	GPIO_Handle_C_Btn->pGPIO = GPIOC;
	GPIO_Handle_C_Btn->GPIO_PinConfig.GPIO_pinNumber = GPIO_PIN_NO_13;
	GPIO_Handle_C_Btn->GPIO_PinConfig.GPIO_pinMode = GPIO_MODE_IN;
	GPIO_Handle_C_Btn -> GPIO_PinConfig.PinPupdControl = GPIO_PD ;
	GPIO_Handle_C_Btn->GPIO_PinConfig.GPIO_pin_speed = GPIO_SPEED_FAST;

	GPIO_PeriClockControl(GPIO_Handle_C_Btn->pGPIO,1);
	GPIO_Init(GPIO_Handle_C_Btn);
	uint8_t volatile PC13_Pin;
	while(1){
		PC13_Pin = GPIO_ReadFromInputPin(GPIO_Handle_C_Btn->pGPIO, GPIO_PIN_NO_13);
		if (PC13_Pin == 0){
			delay();
			GPIO_ToggIeOutputPin(GPIO_Handle_A->pGPIO,GPIO_Handle_A->GPIO_PinConfig.GPIO_pinNumber);
		}
	}


}
